## Basys 3 constraints for Nanoprocessor_Basys3

## 100 MHz clock
set_property PACKAGE_PIN W5 [get_ports Clk]
set_property IOSTANDARD LVCMOS33 [get_ports Clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports Clk]

## Reset and manual step input
set_property PACKAGE_PIN U18 [get_ports Reset]
set_property IOSTANDARD LVCMOS33 [get_ports Reset]

set_property PACKAGE_PIN T17 [get_ports Btn_Step]
set_property IOSTANDARD LVCMOS33 [get_ports Btn_Step]

## Switches
set_property PACKAGE_PIN V17 [get_ports {Sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sw[0]}]
set_property PACKAGE_PIN V16 [get_ports {Sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sw[1]}]
set_property PACKAGE_PIN W16 [get_ports {Sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sw[2]}]
set_property PACKAGE_PIN W17 [get_ports {Sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sw[3]}]
set_property PACKAGE_PIN W15 [get_ports {Sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sw[4]}]
set_property PACKAGE_PIN V15 [get_ports {Sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sw[5]}]
set_property PACKAGE_PIN W14 [get_ports {Sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sw[6]}]
set_property PACKAGE_PIN W13 [get_ports {Sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sw[7]}]
set_property PACKAGE_PIN V2 [get_ports {Sw[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sw[8]}]
set_property PACKAGE_PIN T3 [get_ports {Sw[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sw[9]}]
set_property PACKAGE_PIN T2 [get_ports {Sw[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sw[10]}]
set_property PACKAGE_PIN R3 [get_ports {Sw[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sw[11]}]
set_property PACKAGE_PIN W2 [get_ports {Sw[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sw[12]}]
set_property PACKAGE_PIN U1 [get_ports {Sw[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sw[13]}]
set_property PACKAGE_PIN T1 [get_ports {Sw[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sw[14]}]
set_property PACKAGE_PIN R2 [get_ports {Sw[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sw[15]}]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {Led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[0]}]
set_property PACKAGE_PIN E19 [get_ports {Led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[1]}]
set_property PACKAGE_PIN U19 [get_ports {Led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[2]}]
set_property PACKAGE_PIN V19 [get_ports {Led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[3]}]
set_property PACKAGE_PIN W18 [get_ports {Led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[4]}]
set_property PACKAGE_PIN U15 [get_ports {Led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[5]}]
set_property PACKAGE_PIN U14 [get_ports {Led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[6]}]
set_property PACKAGE_PIN V14 [get_ports {Led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[7]}]
set_property PACKAGE_PIN V13 [get_ports {Led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[8]}]
set_property PACKAGE_PIN V3 [get_ports {Led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[9]}]
set_property PACKAGE_PIN W3 [get_ports {Led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[10]}]
set_property PACKAGE_PIN U3 [get_ports {Led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[11]}]
set_property PACKAGE_PIN P3 [get_ports {Led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[12]}]
set_property PACKAGE_PIN N3 [get_ports {Led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[13]}]
set_property PACKAGE_PIN P1 [get_ports {Led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[14]}]
set_property PACKAGE_PIN L1 [get_ports {Led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[15]}]

## Seven-segment segments, active-low
set_property PACKAGE_PIN W7 [get_ports {Seg_Out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Out[0]}]
set_property PACKAGE_PIN W6 [get_ports {Seg_Out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Out[1]}]
set_property PACKAGE_PIN U8 [get_ports {Seg_Out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Out[2]}]
set_property PACKAGE_PIN V8 [get_ports {Seg_Out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Out[3]}]
set_property PACKAGE_PIN U5 [get_ports {Seg_Out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Out[4]}]
set_property PACKAGE_PIN V5 [get_ports {Seg_Out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Out[5]}]
set_property PACKAGE_PIN U7 [get_ports {Seg_Out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Out[6]}]

## Seven-segment anodes, active-low
set_property PACKAGE_PIN U2 [get_ports {Anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[0]}]
set_property PACKAGE_PIN U4 [get_ports {Anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[1]}]
set_property PACKAGE_PIN V4 [get_ports {Anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[2]}]
set_property PACKAGE_PIN W4 [get_ports {Anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[3]}]
